name: Build Package Scry
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build Pacakge Scry
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dist
        env:
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}

