name: Build Package Scry
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build Pacakge Scry
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ RELEASE_VERSION }}
          tag_name: ${{ RELEASE_VERSION }}
          files: out/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
